### ISSUE TITLE
Load fonts from disk, not Google Fonts

### ISSUE THREAD

**Issue by kazigk** [Bartozzz/Qilin#19]

**Comment by kinnerapriyap** [comment]
Does this have to be done for all the fonts referenced in the code?

**Comment by kinnerapriyap** [comment]
#22

**Comment by Bartozzz** [comment]
We should store all the fonts locally as those doesn't change too often (at all?).
Thanks for you PR by the way. 😄

**Comment by Bartozzz** [comment]
Closed #22
