### ISSUE TITLE
Long startup of Qilin

### ISSUE THREAD

**Issue by Albert221** [Bartozzz/Qilin#6]
From opening app.exe to window's appear there is like 1.5 minutes. After opening app.exe it goes to task manager.

Ran on SSD, Windows 10 Pro x64 Redstone.

**Comment by Bartozzz** [comment]
Right now, there are some resources that are loaded from internet at the startup (fonts, some style files, etc.). Maybe that's the reason why the app freezes on launch on some devices. Normally it should take less than 5 seconds to open.
