### ISSUE TITLE
Only symbol clickable in split view and theme buttons

### ISSUE THREAD

**Issue by Albert221** [Bartozzz/Qilin#7]
As in title. Windows 10 Pro x64 Redstone

https://gfycat.com/AdmiredBewitchedCooter

**Comment by Bartozzz** [comment]
This is actually a bug in NW.js. There's no way I can fix it.

>Beware, if frame is set to false in fullscreen it will prevent the mouse from being captured on the very edges of the screen. You should avoid activate it if fullscreen is also set to true.
[NW.js Documentation](http://docs.nwjs.io/en/latest/References/Manifest%20Format/#frame)
